/**
 * Strings de telemetria/gastos do Moka (pedido do Miguel, 2026-08-22).
 *
 * Dicionário próprio (em vez de entupir o ui-strings.ts) porque o tema é
 * novo e autocontido: pop-up de consumo, preferências de aviso/trava e a
 * página /telemetria. Mesmos 12 idiomas da interface.
 *
 * Uso: `tt(lang, "tele_total")` — cai pra inglês, depois pt-BR.
 */

export type TeleStringKey =
  // ── Página /telemetria ("Suas IAs" — reforma do Miguel, 22/08) ──
  | "tele_nav"
  | "tele_page_title"
  | "tele_intro"
  | "tele_your_ais"
  | "tele_no_ais"
  | "tele_add_key"
  | "tele_spend_title"
  | "tele_ai_spent"
  | "tele_open_settings"
  | "tele_banner_sub"
  | "tele_total"
  | "tele_by_task"
  | "tele_by_provider"
  | "tele_by_model"
  | "tele_history"
  | "tele_clear"
  | "tele_clear_confirm"
  | "tele_export_csv"
  | "tele_currency"
  | "tele_approx"
  | "tele_empty"
  | "tele_tokens"
  | "tele_calls"
  | "tele_cost"
  | "tele_task"
  | "tele_provider"
  | "tele_model"
  | "tele_status"
  | "tele_ok"
  | "tele_err"
  // ── Pop-up de consumo ──
  | "usage_title"
  | "usage_in"
  | "usage_out"
  | "usage_cost"
  | "usage_dontshow"
  | "usage_view"
  | "usage_cap_warning"
  | "usage_error_note"
  | "usage_estimated"
  // ── Configurações: avisos e trava ──
  | "set_usage_title"
  | "set_usage_popup"
  | "set_usage_always"
  | "set_usage_above"
  | "set_usage_off"
  | "set_usage_threshold"
  | "set_usage_cap"
  | "set_usage_cap_hint"
  | "set_balance_btn"
  | "set_balance_unsupported"
  | "set_balance_open_panel"
  | "set_model_btn"
  // ── Rótulos de tarefa (ledger) ──
  | "task_translate"
  | "task_translate_page"
  | "task_translate_page_image"
  | "tele_charts_title"
  | "tele_charts_cost"
  | "tele_charts_tokens"
  | "tele_charts_all"
  | "tele_charts_empty"
  | "tele_mural_btn"
  | "usage_ok"
  | "usage_copy"
  | "usage_copied"
  | "usage_telemetry_note"
  | "tele_total_all"
  | "tele_total_7"
  | "tele_total_30"
  | "task_translate_speech"
  | "task_explain"
  | "task_explain_page"
  | "task_ask"
  | "task_summarize_page"
  | "task_summarize_book"
  | "task_tts"
  | "task_test"
  | "task_video_explain"
  | "task_video_summarize"
  | "task_video_characters"
  | "task_video_political"
  | "task_video_critique"
  | "task_video_correct"
  | "task_video_ask";

type TeleStrings = Record<TeleStringKey, string>;

const STRINGS: Record<string, TeleStrings> = {
  "pt-BR": {
    tele_nav: "Suas IAs e telemetria",
    tele_page_title: "Suas IAs",
    tele_intro:
      "A página de controle das suas IAs: veja as chaves registradas, troque o modelo de cada uma e acompanhe quanto cada tarefa gastou. Tudo registrado só no seu dispositivo.",
    tele_your_ais: "Suas IAs registradas",
    tele_no_ais:
      "Você ainda não registrou nenhuma chave de IA. Adicione a primeira para começar.",
    tele_add_key: "➕ Adicionar chave de IA",
    tele_spend_title: "📊 Gastos por uso",
    tele_ai_spent: "Gasto desta IA",
    tele_open_settings: "⚙️ Abrir configurações completas",
    tele_banner_sub:
      "Veja suas IAs, troque o modelo e acompanhe cada gasto",
    tele_total: "Total gasto",
    tele_by_task: "Por tarefa",
    tele_by_provider: "Por IA (provedor)",
    tele_by_model: "Por modelo",
    tele_history: "Histórico",
    tele_clear: "Limpar histórico",
    tele_clear_confirm:
      "Apagar TODO o histórico de gastos? Isso não pode ser desfeito (os registros ficam só neste dispositivo).",
    tele_export_csv: "Baixar CSV",
    tele_currency: "Moeda local",
    tele_approx:
      "Valores estimados — câmbio e preços aproximados, não é fatura oficial.",
    tele_empty:
      "Nenhum gasto registrado ainda. Use traduzir, explicar, perguntar, voz ou vídeo — cada consumo aparece aqui.",
    tele_tokens: "tokens",
    tele_calls: "chamadas",
    tele_cost: "custo",
    tele_task: "tarefa",
    tele_provider: "IA",
    tele_model: "modelo",
    tele_status: "status",
    tele_ok: "ok",
    tele_err: "erro",
    usage_title: "Consumo de IA",
    usage_in: "entrada",
    usage_out: "saída",
    usage_cost: "Custo estimado",
    usage_dontshow: "Não quero mais ver isso",
    usage_view: "Ver telemetria",
    usage_cap_warning: "⚠️ Passou da sua trava de tokens por tarefa!",
    usage_error_note:
      "⚠️ A tarefa falhou — sua chave pode estar inválida ou sem crédito.",
    usage_estimated: "estimado",
    set_usage_title: "💸 Avisos e trava de consumo",
    set_usage_popup: "Informe de consumo (pop-up)",
    set_usage_always: "Sempre mostrar",
    set_usage_above: "Só quando passar de",
    set_usage_off: "Nunca mostrar",
    set_usage_threshold: "tokens",
    set_usage_cap: "Trava de tokens por tarefa (0 = sem trava)",
    set_usage_cap_hint:
      "Se uma tarefa passar do limite, o Moka avisa e interrompe sem travar — você nunca perde o controle do gasto.",
    set_balance_btn: "💰 Ver saldo",
    set_balance_unsupported:
      "Este provedor não expõe o saldo via API. Consulte o painel oficial:",
    set_balance_open_panel: "Abrir painel do provedor",
    set_model_btn: "Trocar modelo",
    task_translate: "Tradução (trecho)",
    task_translate_page: "Tradução de página",
    task_translate_page_image: "Tradução de página (imagem)",
    tele_charts_title: "Evolução dos gastos (14 dias)",
    tele_charts_cost: "Custo (US$)",
    tele_charts_tokens: "Tokens",
    tele_charts_all: "Todas",
    tele_charts_empty: "Ainda sem dados suficientes pra desenhar os gráficos — use o Moka um pouco mais.",
    tele_mural_btn: "🏆 Mural das IAs",
    usage_ok: "OK",
    usage_copy: "Copiar",
    usage_copied: "Copiado ✓",
    usage_telemetry_note: "Os gastos serão guardados na sua página de telemetria.",
    tele_total_all: "Desde o início (neste dispositivo)",
    tele_total_7: "Últimos 7 dias",
    tele_total_30: "Últimos 30 dias",
    task_translate_speech: "Tradução para fala",
    task_explain: "Explicação (trecho)",
    task_explain_page: "Explicação de página",
    task_ask: "Pergunta sobre o livro",
    task_summarize_page: "Resumo de página",
    task_summarize_book: "Resumo do livro",
    task_tts: "Voz neural (TTS)",
    task_test: "Teste de conexão",
    task_video_explain: "Vídeo: explicação rápida",
    task_video_summarize: "Vídeo: resumo",
    task_video_characters: "Vídeo: personagens",
    task_video_political: "Vídeo: contexto político",
    task_video_critique: "Vídeo: crítica",
    task_video_correct: "Vídeo: transcrição corrigida",
    task_video_ask: "Vídeo: pergunta",
  },
  en: {
    tele_nav: "Your AIs & telemetry",
    tele_page_title: "Your AIs",
    tele_intro:
      "Your AI control page: see your registered keys, switch each one's model and track how much each task spent. Everything recorded only on your device.",
    tele_your_ais: "Your registered AIs",
    tele_no_ais: "You haven't registered any AI key yet. Add the first one to start.",
    tele_add_key: "➕ Add AI key",
    tele_spend_title: "📊 Usage spending",
    tele_ai_spent: "Spent by this AI",
    tele_open_settings: "⚙️ Open full settings",
    tele_banner_sub: "See your AIs, switch models and track every cost",
    tele_total: "Total spent",
    tele_by_task: "By task",
    tele_by_provider: "By AI (provider)",
    tele_by_model: "By model",
    tele_history: "History",
    tele_clear: "Clear history",
    tele_clear_confirm:
      "Delete ALL spending history? This cannot be undone (records live only on this device).",
    tele_export_csv: "Download CSV",
    tele_currency: "Local currency",
    tele_approx:
      "Estimated values — approximate exchange rates and prices, not an official invoice.",
    tele_empty:
      "No spending recorded yet. Use translate, explain, ask, voice or video — every use shows up here.",
    tele_tokens: "tokens",
    tele_calls: "calls",
    tele_cost: "cost",
    tele_task: "task",
    tele_provider: "AI",
    tele_model: "model",
    tele_status: "status",
    tele_ok: "ok",
    tele_err: "error",
    usage_title: "AI usage",
    usage_in: "input",
    usage_out: "output",
    usage_cost: "Estimated cost",
    usage_dontshow: "Don't show this again",
    usage_view: "View telemetry",
    usage_cap_warning: "⚠️ Went over your per-task token cap!",
    usage_error_note:
      "⚠️ The task failed — your key may be invalid or out of credit.",
    usage_estimated: "estimated",
    set_usage_title: "💸 Usage warnings and cap",
    set_usage_popup: "Usage report (pop-up)",
    set_usage_always: "Always show",
    set_usage_above: "Only above",
    set_usage_off: "Never show",
    set_usage_threshold: "tokens",
    set_usage_cap: "Token cap per task (0 = no cap)",
    set_usage_cap_hint:
      "If a task goes over the limit, Moka warns you and stops it without freezing — you stay in control of your spend.",
    set_balance_btn: "💰 Check balance",
    set_balance_unsupported:
      "This provider does not expose balance via API. Check its official dashboard:",
    set_balance_open_panel: "Open provider dashboard",
    set_model_btn: "Change model",
    task_translate: "Translation (snippet)",
    task_translate_page: "Page translation",
    task_translate_page_image: "Page translation (image)",
    tele_charts_title: "Spending over time (14 days)",
    tele_charts_cost: "Cost (US$)",
    tele_charts_tokens: "Tokens",
    tele_charts_all: "All",
    tele_charts_empty: "Not enough data for charts yet — keep using Moka.",
    tele_mural_btn: "🏆 AI Wall",
    usage_ok: "OK",
    usage_copy: "Copy",
    usage_copied: "Copied ✓",
    usage_telemetry_note: "Your spending is saved on your telemetry page.",
    tele_total_all: "All time (this device)",
    tele_total_7: "Last 7 days",
    tele_total_30: "Last 30 days",
    task_translate_speech: "Translation for speech",
    task_explain: "Explanation (snippet)",
    task_explain_page: "Page explanation",
    task_ask: "Book question",
    task_summarize_page: "Page summary",
    task_summarize_book: "Book summary",
    task_tts: "Neural voice (TTS)",
    task_test: "Connection test",
    task_video_explain: "Video: quick explanation",
    task_video_summarize: "Video: summary",
    task_video_characters: "Video: characters",
    task_video_political: "Video: political context",
    task_video_critique: "Video: critique",
    task_video_correct: "Video: corrected transcript",
    task_video_ask: "Video: question",
  },
  es: {
    tele_nav: "Tus IAs y telemetría",
    tele_page_title: "Tus IAs",
    tele_intro:
      "La página de control de tus IAs: ve tus claves registradas, cambia el modelo de cada una y mira cuánto gastó cada tarea. Todo registrado solo en tu dispositivo.",
    tele_your_ais: "Tus IAs registradas",
    tele_no_ais: "Aún no registraste ninguna clave de IA. Agrega la primera para empezar.",
    tele_add_key: "➕ Agregar clave de IA",
    tele_spend_title: "📊 Gastos por uso",
    tele_ai_spent: "Gasto de esta IA",
    tele_open_settings: "⚙️ Abrir configuraciones completas",
    tele_banner_sub: "Mira tus IAs, cambia el modelo y sigue cada gasto",
    tele_total: "Total gastado",
    tele_by_task: "Por tarea",
    tele_by_provider: "Por IA (proveedor)",
    tele_by_model: "Por modelo",
    tele_history: "Historial",
    tele_clear: "Borrar historial",
    tele_clear_confirm:
      "¿Borrar TODO el historial de gastos? No se puede deshacer (los registros viven solo en este dispositivo).",
    tele_export_csv: "Descargar CSV",
    tele_currency: "Moneda local",
    tele_approx:
      "Valores estimados — cambio y precios aproximados, no es una factura oficial.",
    tele_empty:
      "Aún no hay gastos registrados. Usa traducir, explicar, preguntar, voz o video — cada consumo aparece aquí.",
    tele_tokens: "tokens",
    tele_calls: "llamadas",
    tele_cost: "costo",
    tele_task: "tarea",
    tele_provider: "IA",
    tele_model: "modelo",
    tele_status: "estado",
    tele_ok: "ok",
    tele_err: "error",
    usage_title: "Consumo de IA",
    usage_in: "entrada",
    usage_out: "salida",
    usage_cost: "Costo estimado",
    usage_dontshow: "No quiero ver esto más",
    usage_view: "Ver telemetría",
    usage_cap_warning: "⚠️ ¡Superó tu límite de tokens por tarea!",
    usage_error_note:
      "⚠️ La tarea falló — tu clave puede ser inválida o estar sin crédito.",
    usage_estimated: "estimado",
    set_usage_title: "💸 Avisos y límite de consumo",
    set_usage_popup: "Informe de consumo (pop-up)",
    set_usage_always: "Mostrar siempre",
    set_usage_above: "Solo cuando supere",
    set_usage_off: "No mostrar nunca",
    set_usage_threshold: "tokens",
    set_usage_cap: "Límite de tokens por tarea (0 = sin límite)",
    set_usage_cap_hint:
      "Si una tarea supera el límite, Moka avisa y la detiene sin congelarse — nunca pierdes el control del gasto.",
    set_balance_btn: "💰 Ver saldo",
    set_balance_unsupported:
      "Este proveedor no expone el saldo vía API. Consulta su panel oficial:",
    set_balance_open_panel: "Abrir panel del proveedor",
    set_model_btn: "Cambiar modelo",
    task_translate: "Traducción (fragmento)",
    task_translate_page: "Traducción de página",
    task_translate_page_image: "Traducción de página (imagen)",
    tele_charts_title: "Evolución del gasto (14 días)",
    tele_charts_cost: "Costo (US$)",
    tele_charts_tokens: "Tokens",
    tele_charts_all: "Todas",
    tele_charts_empty: "Todavía no hay datos suficientes para los gráficos — sigue usando Moka.",
    tele_mural_btn: "🏆 Mural de IAs",
    usage_ok: "OK",
    usage_copy: "Copiar",
    usage_copied: "Copiado ✓",
    usage_telemetry_note: "Los gastos se guardan en tu página de telemetría.",
    tele_total_all: "Desde el inicio (en este dispositivo)",
    tele_total_7: "Últimos 7 días",
    tele_total_30: "Últimos 30 días",
    task_translate_speech: "Traducción para voz",
    task_explain: "Explicación (fragmento)",
    task_explain_page: "Explicación de página",
    task_ask: "Pregunta sobre el libro",
    task_summarize_page: "Resumen de página",
    task_summarize_book: "Resumen del libro",
    task_tts: "Voz neural (TTS)",
    task_test: "Prueba de conexión",
    task_video_explain: "Video: explicación rápida",
    task_video_summarize: "Video: resumen",
    task_video_characters: "Video: personajes",
    task_video_political: "Video: contexto político",
    task_video_critique: "Video: crítica",
    task_video_correct: "Video: transcripción corregida",
    task_video_ask: "Video: pregunta",
  },
  fr: {
    tele_nav: "Vos IA et télémétrie",
    tele_page_title: "Vos IA",
    tele_intro:
      "La page de contrôle de vos IA : voyez vos clés enregistrées, changez le modèle de chacune et suivez ce que chaque tâche a consommé. Tout reste sur votre appareil.",
    tele_your_ais: "Vos IA enregistrées",
    tele_no_ais: "Vous n'avez encore enregistré aucune clé d'IA. Ajoutez la première pour commencer.",
    tele_add_key: "➕ Ajouter une clé d'IA",
    tele_spend_title: "📊 Dépenses par usage",
    tele_ai_spent: "Dépensé par cette IA",
    tele_open_settings: "⚙️ Ouvrir tous les réglages",
    tele_banner_sub: "Voyez vos IA, changez de modèle et suivez chaque dépense",
    tele_total: "Total dépensé",
    tele_by_task: "Par tâche",
    tele_by_provider: "Par IA (fournisseur)",
    tele_by_model: "Par modèle",
    tele_history: "Historique",
    tele_clear: "Effacer l'historique",
    tele_clear_confirm:
      "Supprimer TOUT l'historique des dépenses ? Irréversible (les données restent sur cet appareil).",
    tele_export_csv: "Télécharger CSV",
    tele_currency: "Monnaie locale",
    tele_approx:
      "Valeurs estimées — taux et prix approximatifs, pas une facture officielle.",
    tele_empty:
      "Aucune dépense enregistrée. Utilisez traduire, expliquer, demander, voix ou vidéo — chaque consommation apparaît ici.",
    tele_tokens: "tokens",
    tele_calls: "appels",
    tele_cost: "coût",
    tele_task: "tâche",
    tele_provider: "IA",
    tele_model: "modèle",
    tele_status: "statut",
    tele_ok: "ok",
    tele_err: "erreur",
    usage_title: "Consommation d'IA",
    usage_in: "entrée",
    usage_out: "sortie",
    usage_cost: "Coût estimé",
    usage_dontshow: "Ne plus afficher",
    usage_view: "Voir la télémétrie",
    usage_cap_warning: "⚠️ Votre limite de tokens par tâche est dépassée !",
    usage_error_note:
      "⚠️ La tâche a échoué — votre clé est peut-être invalide ou sans crédit.",
    usage_estimated: "estimé",
    set_usage_title: "💸 Avertissements et limite de consommation",
    set_usage_popup: "Rapport de consommation (pop-up)",
    set_usage_always: "Toujours afficher",
    set_usage_above: "Seulement au-delà de",
    set_usage_off: "Ne jamais afficher",
    set_usage_threshold: "tokens",
    set_usage_cap: "Limite de tokens par tâche (0 = sans limite)",
    set_usage_cap_hint:
      "Si une tâche dépasse la limite, Moka vous avertit et l'arrête sans planter — vous gardez le contrôle de vos dépenses.",
    set_balance_btn: "💰 Voir le solde",
    set_balance_unsupported:
      "Ce fournisseur n'expose pas le solde via l'API. Consultez son tableau de bord :",
    set_balance_open_panel: "Ouvrir le tableau de bord",
    set_model_btn: "Changer de modèle",
    task_translate: "Traduction (extrait)",
    task_translate_page: "Traduction de page",
    task_translate_page_image: "Traduction de page (image)",
    tele_charts_title: "Évolution des dépenses (14 jours)",
    tele_charts_cost: "Coût (US$)",
    tele_charts_tokens: "Tokens",
    tele_charts_all: "Toutes",
    tele_charts_empty: "Pas encore assez de données pour les graphiques — continuez à utiliser Moka.",
    tele_mural_btn: "🏆 Mur des IAs",
    usage_ok: "OK",
    usage_copy: "Copier",
    usage_copied: "Copié ✓",
    usage_telemetry_note: "Vos dépenses sont enregistrées sur votre page de télémétrie.",
    tele_total_all: "Depuis le début (cet appareil)",
    tele_total_7: "7 derniers jours",
    tele_total_30: "30 derniers jours",
    task_translate_speech: "Traduction pour la voix",
    task_explain: "Explication (extrait)",
    task_explain_page: "Explication de page",
    task_ask: "Question sur le livre",
    task_summarize_page: "Résumé de page",
    task_summarize_book: "Résumé du livre",
    task_tts: "Voix neurale (TTS)",
    task_test: "Test de connexion",
    task_video_explain: "Vidéo : explication rapide",
    task_video_summarize: "Vidéo : résumé",
    task_video_characters: "Vidéo : personnages",
    task_video_political: "Vidéo : contexte politique",
    task_video_critique: "Vidéo : critique",
    task_video_correct: "Vidéo : transcription corrigée",
    task_video_ask: "Vidéo : question",
  },
  de: {
    tele_nav: "Ihre KIs & Telemetrie",
    tele_page_title: "Ihre KIs",
    tele_intro:
      "Ihre KI-Kontrollseite: registrierte Schlüssel ansehen, Modell wechseln und verfolgen, was jede Aufgabe verbraucht hat. Alles nur auf Ihrem Gerät.",
    tele_your_ais: "Registrierte KIs",
    tele_no_ais: "Sie haben noch keinen KI-Schlüssel registriert. Fügen Sie den ersten hinzu, um zu starten.",
    tele_add_key: "➕ KI-Schlüssel hinzufügen",
    tele_spend_title: "📊 Ausgaben nach Nutzung",
    tele_ai_spent: "Verbrauch dieser KI",
    tele_open_settings: "⚙️ Alle Einstellungen öffnen",
    tele_banner_sub: "KIs ansehen, Modell wechseln, jeden Verbrauch verfolgen",
    tele_total: "Gesamtausgaben",
    tele_by_task: "Nach Aufgabe",
    tele_by_provider: "Nach KI (Anbieter)",
    tele_by_model: "Nach Modell",
    tele_history: "Verlauf",
    tele_clear: "Verlauf löschen",
    tele_clear_confirm:
      "GESAMTEN Ausgabeverlauf löschen? Nicht rückgängig machbar (Daten bleiben auf diesem Gerät).",
    tele_export_csv: "CSV herunterladen",
    tele_currency: "Lokale Währung",
    tele_approx:
      "Geschätzte Werte — ungefähre Kurse und Preise, keine offizielle Rechnung.",
    tele_empty:
      "Noch keine Ausgaben. Nutzen Sie Übersetzen, Erklären, Fragen, Stimme oder Video — jeder Verbrauch erscheint hier.",
    tele_tokens: "Tokens",
    tele_calls: "Aufrufe",
    tele_cost: "Kosten",
    tele_task: "Aufgabe",
    tele_provider: "KI",
    tele_model: "Modell",
    tele_status: "Status",
    tele_ok: "ok",
    tele_err: "Fehler",
    usage_title: "KI-Verbrauch",
    usage_in: "Eingabe",
    usage_out: "Ausgabe",
    usage_cost: "Geschätzte Kosten",
    usage_dontshow: "Nicht mehr anzeigen",
    usage_view: "Telemetrie ansehen",
    usage_cap_warning: "⚠️ Ihr Token-Limit pro Aufgabe wurde überschritten!",
    usage_error_note:
      "⚠️ Die Aufgabe ist fehlgeschlagen — Ihr Schlüssel ist evtl. ungültig oder ohne Guthaben.",
    usage_estimated: "geschätzt",
    set_usage_title: "💸 Warnungen und Verbrauchs-Limit",
    set_usage_popup: "Verbrauchsbericht (Pop-up)",
    set_usage_always: "Immer anzeigen",
    set_usage_above: "Nur über",
    set_usage_off: "Nie anzeigen",
    set_usage_threshold: "Tokens",
    set_usage_cap: "Token-Limit pro Aufgabe (0 = kein Limit)",
    set_usage_cap_hint:
      "Überschreitet eine Aufgabe das Limit, warnt Moka und stoppt sie, ohne abzustürzen — Sie behalten die Kontrolle.",
    set_balance_btn: "💰 Guthaben prüfen",
    set_balance_unsupported:
      "Dieser Anbieter gibt das Guthaben nicht per API frei. Nutzen Sie dessen Dashboard:",
    set_balance_open_panel: "Anbieter-Dashboard öffnen",
    set_model_btn: "Modell wechseln",
    task_translate: "Übersetzung (Ausschnitt)",
    task_translate_page: "Seitenübersetzung",
    task_translate_page_image: "Seitenübersetzung (Bild)",
    tele_charts_title: "Ausgabenverlauf (14 Tage)",
    tele_charts_cost: "Kosten (US$)",
    tele_charts_tokens: "Tokens",
    tele_charts_all: "Alle",
    tele_charts_empty: "Noch nicht genug Daten für Diagramme — nutze Moka weiter.",
    tele_mural_btn: "🏆 KI-Wand",
    usage_ok: "OK",
    usage_copy: "Kopieren",
    usage_copied: "Kopiert ✓",
    usage_telemetry_note: "Deine Ausgaben werden auf deiner Telemetrie-Seite gespeichert.",
    tele_total_all: "Gesamt (dieses Gerät)",
    tele_total_7: "Letzte 7 Tage",
    tele_total_30: "Letzte 30 Tage",
    task_translate_speech: "Übersetzung für Sprache",
    task_explain: "Erklärung (Ausschnitt)",
    task_explain_page: "Seitenerklärung",
    task_ask: "Frage zum Buch",
    task_summarize_page: "Seitenzusammenfassung",
    task_summarize_book: "Buchzusammenfassung",
    task_tts: "Neurale Stimme (TTS)",
    task_test: "Verbindungstest",
    task_video_explain: "Video: Schnellerklärung",
    task_video_summarize: "Video: Zusammenfassung",
    task_video_characters: "Video: Figuren",
    task_video_political: "Video: politischer Kontext",
    task_video_critique: "Video: Kritik",
    task_video_correct: "Video: korrigiertes Transkript",
    task_video_ask: "Video: Frage",
  },
  it: {
    tele_nav: "Le tue AI e telemetria",
    tele_page_title: "Le tue AI",
    tele_intro:
      "La pagina di controllo delle tue AI: vedi le chiavi registrate, cambia il modello di ciascuna e controlla quanto ha speso ogni attività. Tutto solo sul tuo dispositivo.",
    tele_your_ais: "Le tue AI registrate",
    tele_no_ais: "Non hai ancora registrato nessuna chiave AI. Aggiungi la prima per iniziare.",
    tele_add_key: "➕ Aggiungi chiave AI",
    tele_spend_title: "📊 Spese per uso",
    tele_ai_spent: "Speso da questa AI",
    tele_open_settings: "⚙️ Apri impostazioni complete",
    tele_banner_sub: "Vedi le tue AI, cambia modello e segui ogni spesa",
    tele_total: "Totale speso",
    tele_by_task: "Per attività",
    tele_by_provider: "Per AI (provider)",
    tele_by_model: "Per modello",
    tele_history: "Cronologia",
    tele_clear: "Cancella cronologia",
    tele_clear_confirm:
      "Eliminare TUTTA la cronologia delle spese? Non è reversibile (i dati restano su questo dispositivo).",
    tele_export_csv: "Scarica CSV",
    tele_currency: "Valuta locale",
    tele_approx:
      "Valori stimati — cambio e prezzi approssimativi, non è una fattura ufficiale.",
    tele_empty:
      "Nessuna spesa registrata. Usa tradurre, spiegare, chiedere, voce o video — ogni consumo appare qui.",
    tele_tokens: "token",
    tele_calls: "chiamate",
    tele_cost: "costo",
    tele_task: "attività",
    tele_provider: "AI",
    tele_model: "modello",
    tele_status: "stato",
    tele_ok: "ok",
    tele_err: "errore",
    usage_title: "Consumo AI",
    usage_in: "ingresso",
    usage_out: "uscita",
    usage_cost: "Costo stimato",
    usage_dontshow: "Non mostrare più",
    usage_view: "Vedi telemetria",
    usage_cap_warning: "⚠️ Superato il tuo limite di token per attività!",
    usage_error_note:
      "⚠️ L'attività è fallita — la chiave potrebbe essere invalida o senza credito.",
    usage_estimated: "stimato",
    set_usage_title: "💸 Avvisi e limite di consumo",
    set_usage_popup: "Report di consumo (pop-up)",
    set_usage_always: "Mostra sempre",
    set_usage_above: "Solo oltre",
    set_usage_off: "Non mostrare mai",
    set_usage_threshold: "token",
    set_usage_cap: "Limite di token per attività (0 = nessun limite)",
    set_usage_cap_hint:
      "Se un'attività supera il limite, Moka avvisa e la ferma senza bloccarsi — mantieni il controllo della spesa.",
    set_balance_btn: "💰 Vedi saldo",
    set_balance_unsupported:
      "Questo provider non espone il saldo via API. Consulta il suo pannello ufficiale:",
    set_balance_open_panel: "Apri pannello del provider",
    set_model_btn: "Cambia modello",
    task_translate: "Traduzione (brano)",
    task_translate_page: "Traduzione pagina",
    task_translate_page_image: "Traduzione pagina (immagine)",
    tele_charts_title: "Andamento delle spese (14 giorni)",
    tele_charts_cost: "Costo (US$)",
    tele_charts_tokens: "Token",
    tele_charts_all: "Tutte",
    tele_charts_empty: "Ancora pochi dati per i grafici — continua a usare Moka.",
    tele_mural_btn: "🏆 Muro delle IA",
    usage_ok: "OK",
    usage_copy: "Copia",
    usage_copied: "Copiato ✓",
    usage_telemetry_note: "Le spese vengono salvate nella tua pagina di telemetria.",
    tele_total_all: "Dall'inizio (questo dispositivo)",
    tele_total_7: "Ultimi 7 giorni",
    tele_total_30: "Ultimi 30 giorni",
    task_translate_speech: "Traduzione per la voce",
    task_explain: "Spiegazione (brano)",
    task_explain_page: "Spiegazione pagina",
    task_ask: "Domanda sul libro",
    task_summarize_page: "Riassunto pagina",
    task_summarize_book: "Riassunto del libro",
    task_tts: "Voce neurale (TTS)",
    task_test: "Test di connessione",
    task_video_explain: "Video: spiegazione rapida",
    task_video_summarize: "Video: riassunto",
    task_video_characters: "Video: personaggi",
    task_video_political: "Video: contesto politico",
    task_video_critique: "Video: critica",
    task_video_correct: "Video: trascrizione corretta",
    task_video_ask: "Video: domanda",
  },
  ru: {
    tele_nav: "Ваши ИИ и телеметрия",
    tele_page_title: "Ваши ИИ",
    tele_intro:
      "Страница управления вашими ИИ: смотрите зарегистрированные ключи, меняйте модель и следите, сколько потратила каждая задача. Всё только на вашем устройстве.",
    tele_your_ais: "Зарегистрированные ИИ",
    tele_no_ais: "Вы ещё не зарегистрировали ни одного ключа ИИ. Добавьте первый, чтобы начать.",
    tele_add_key: "➕ Добавить ключ ИИ",
    tele_spend_title: "📊 Расходы по использованию",
    tele_ai_spent: "Потрачено этим ИИ",
    tele_open_settings: "⚙️ Открыть все настройки",
    tele_banner_sub: "Смотрите ИИ, меняйте модели, следите за расходами",
    tele_total: "Всего потрачено",
    tele_by_task: "По задаче",
    tele_by_provider: "По ИИ (провайдеру)",
    tele_by_model: "По модели",
    tele_history: "История",
    tele_clear: "Очистить историю",
    tele_clear_confirm:
      "Удалить ВСЮ историю расходов? Это необратимо (записи хранятся только на этом устройстве).",
    tele_export_csv: "Скачать CSV",
    tele_currency: "Местная валюта",
    tele_approx:
      "Оценочные значения — приблизительный курс и цены, не официальный счёт.",
    tele_empty:
      "Расходов пока нет. Переводите, объясняйте, спрашивайте, озвучивайте — каждый расход появится здесь.",
    tele_tokens: "токенов",
    tele_calls: "вызовов",
    tele_cost: "стоимость",
    tele_task: "задача",
    tele_provider: "ИИ",
    tele_model: "модель",
    tele_status: "статус",
    tele_ok: "ок",
    tele_err: "ошибка",
    usage_title: "Потребление ИИ",
    usage_in: "вход",
    usage_out: "выход",
    usage_cost: "Оценка стоимости",
    usage_dontshow: "Больше не показывать",
    usage_view: "Открыть телеметрию",
    usage_cap_warning: "⚠️ Превышен ваш лимит токенов на задачу!",
    usage_error_note:
      "⚠️ Задача не выполнена — ключ может быть недействителен или без кредита.",
    usage_estimated: "оценка",
    set_usage_title: "💸 Предупреждения и лимит потребления",
    set_usage_popup: "Отчёт о потреблении (попап)",
    set_usage_always: "Показывать всегда",
    set_usage_above: "Только свыше",
    set_usage_off: "Никогда не показывать",
    set_usage_threshold: "токенов",
    set_usage_cap: "Лимит токенов на задачу (0 = без лимита)",
    set_usage_cap_hint:
      "Если задача превысит лимит, Moka предупредит и остановит её без зависания — вы контролируете расходы.",
    set_balance_btn: "💰 Проверить баланс",
    set_balance_unsupported:
      "Этот провайдер не отдаёт баланс через API. Смотрите его панель:",
    set_balance_open_panel: "Открыть панель провайдера",
    set_model_btn: "Сменить модель",
    task_translate: "Перевод (фрагмент)",
    task_translate_page: "Перевод страницы",
    task_translate_page_image: "Перевод страницы (изображение)",
    tele_charts_title: "Динамика расходов (14 дней)",
    tele_charts_cost: "Стоимость (US$)",
    tele_charts_tokens: "Токены",
    tele_charts_all: "Все",
    tele_charts_empty: "Данных для графиков пока мало — пользуйтесь Moka ещё немного.",
    tele_mural_btn: "🏆 Стена ИИ",
    usage_ok: "OK",
    usage_copy: "Копировать",
    usage_copied: "Скопировано ✓",
    usage_telemetry_note: "Расходы сохраняются на вашей странице телеметрии.",
    tele_total_all: "За всё время (это устройство)",
    tele_total_7: "Последние 7 дней",
    tele_total_30: "Последние 30 дней",
    task_translate_speech: "Перевод для озвучки",
    task_explain: "Объяснение (фрагмент)",
    task_explain_page: "Объяснение страницы",
    task_ask: "Вопрос о книге",
    task_summarize_page: "Краткое содержание страницы",
    task_summarize_book: "Краткое содержание книги",
    task_tts: "Нейроголос (TTS)",
    task_test: "Проверка соединения",
    task_video_explain: "Видео: быстрое объяснение",
    task_video_summarize: "Видео: краткое содержание",
    task_video_characters: "Видео: персонажи",
    task_video_political: "Видео: политический контекст",
    task_video_critique: "Видео: критика",
    task_video_correct: "Видео: исправленная транскрипция",
    task_video_ask: "Видео: вопрос",
  },
  zh: {
    tele_nav: "您的 AI 与遥测",
    tele_page_title: "您的 AI",
    tele_intro:
      "您的 AI 控制页：查看已注册的密钥、更换每个密钥的模型，并跟踪每项任务的花费。所有记录仅保存在您的设备上。",
    tele_your_ais: "已注册的 AI",
    tele_no_ais: "您还没有注册任何 AI 密钥。添加第一个即可开始。",
    tele_add_key: "➕ 添加 AI 密钥",
    tele_spend_title: "📊 使用支出",
    tele_ai_spent: "该 AI 的花费",
    tele_open_settings: "⚙️ 打开完整设置",
    tele_banner_sub: "查看 AI、更换模型、跟踪每笔花费",
    tele_total: "总支出",
    tele_by_task: "按任务",
    tele_by_provider: "按 AI（提供商）",
    tele_by_model: "按模型",
    tele_history: "历史记录",
    tele_clear: "清除历史",
    tele_clear_confirm: "删除全部消费记录？无法撤销（记录仅保存在本设备）。",
    tele_export_csv: "下载 CSV",
    tele_currency: "本地货币",
    tele_approx: "估算值——汇率与价格均为近似，非官方账单。",
    tele_empty: "暂无消费记录。使用翻译、解释、提问、朗读或视频后，每笔消费都会显示在这里。",
    tele_tokens: "令牌",
    tele_calls: "次调用",
    tele_cost: "成本",
    tele_task: "任务",
    tele_provider: "AI",
    tele_model: "模型",
    tele_status: "状态",
    tele_ok: "正常",
    tele_err: "错误",
    usage_title: "AI 消耗",
    usage_in: "输入",
    usage_out: "输出",
    usage_cost: "估算成本",
    usage_dontshow: "不再显示",
    usage_view: "查看遥测",
    usage_cap_warning: "⚠️ 超过了您的单任务令牌上限！",
    usage_error_note: "⚠️ 任务失败——密钥可能无效或额度已用完。",
    usage_estimated: "估算",
    set_usage_title: "💸 消费提醒与上限",
    set_usage_popup: "消费报告（弹窗）",
    set_usage_always: "总是显示",
    set_usage_above: "仅当超过",
    set_usage_off: "从不显示",
    set_usage_threshold: "个令牌",
    set_usage_cap: "单任务令牌上限（0 = 不限制）",
    set_usage_cap_hint: "任务超过上限时，Moka 会提醒并停止它，不会卡死——消费始终由您掌控。",
    set_balance_btn: "💰 查看余额",
    set_balance_unsupported: "该提供商不通过 API 提供余额，请到官方面板查看：",
    set_balance_open_panel: "打开提供商面板",
    set_model_btn: "更换模型",
    task_translate: "翻译（片段）",
    task_translate_page: "整页翻译",
    task_translate_page_image: "整页翻译（图像）",
    tele_charts_title: "支出趋势（14 天）",
    tele_charts_cost: "费用（US$）",
    tele_charts_tokens: "Token",
    tele_charts_all: "全部",
    tele_charts_empty: "图表数据还不够 — 请继续使用 Moka。",
    tele_mural_btn: "🏆 AI 墙",
    usage_ok: "OK",
    usage_copy: "复制",
    usage_copied: "已复制 ✓",
    usage_telemetry_note: "您的支出已保存在遥测页面。",
    tele_total_all: "总计（本设备）",
    tele_total_7: "最近 7 天",
    tele_total_30: "最近 30 天",
    task_translate_speech: "朗读用翻译",
    task_explain: "解释（片段）",
    task_explain_page: "整页解释",
    task_ask: "书籍提问",
    task_summarize_page: "页面摘要",
    task_summarize_book: "全书摘要",
    task_tts: "神经语音（TTS）",
    task_test: "连接测试",
    task_video_explain: "视频：快速讲解",
    task_video_summarize: "视频：摘要",
    task_video_characters: "视频：人物",
    task_video_political: "视频：政治背景",
    task_video_critique: "视频：评论",
    task_video_correct: "视频：校对转录",
    task_video_ask: "视频：提问",
  },
  ja: {
    tele_nav: "AIとテレメトリ",
    tele_page_title: "あなたのAI",
    tele_intro:
      "AIコントロールページ：登録済みのキーを確認し、モデルを切り替え、各タスクの消費を追跡します。記録はすべて端末内にのみ保存されます。",
    tele_your_ais: "登録済みのAI",
    tele_no_ais: "まだAIキーが登録されていません。最初のキーを追加して始めましょう。",
    tele_add_key: "➕ AIキーを追加",
    tele_spend_title: "📊 使用量の内訳",
    tele_ai_spent: "このAIの消費",
    tele_open_settings: "⚙️ 全設定を開く",
    tele_banner_sub: "AIを確認し、モデルを変更し、消費を追跡",
    tele_total: "合計支出",
    tele_by_task: "タスク別",
    tele_by_provider: "AI（プロバイダー）別",
    tele_by_model: "モデル別",
    tele_history: "履歴",
    tele_clear: "履歴を消去",
    tele_clear_confirm: "使用履歴をすべて削除しますか？元に戻せません（記録はこの端末内にのみ保存）。",
    tele_export_csv: "CSVをダウンロード",
    tele_currency: "現地通貨",
    tele_approx: "推定値——為替・価格とも概算であり、公式な請求書ではありません。",
    tele_empty: "まだ記録がありません。翻訳・説明・質問・音声・動画を使うと、ここに消費が表示されます。",
    tele_tokens: "トークン",
    tele_calls: "回の呼び出し",
    tele_cost: "コスト",
    tele_task: "タスク",
    tele_provider: "AI",
    tele_model: "モデル",
    tele_status: "状態",
    tele_ok: "OK",
    tele_err: "エラー",
    usage_title: "AI使用量",
    usage_in: "入力",
    usage_out: "出力",
    usage_cost: "推定コスト",
    usage_dontshow: "今後表示しない",
    usage_view: "テレメトリを見る",
    usage_cap_warning: "⚠️ タスクあたりのトークン上限を超えました！",
    usage_error_note: "⚠️ タスクが失敗しました——キーが無効か、クレジット切れの可能性があります。",
    usage_estimated: "推定",
    set_usage_title: "💸 使用量の警告と上限",
    set_usage_popup: "使用量レポート（ポップアップ）",
    set_usage_always: "常に表示",
    set_usage_above: "これを超えたら表示",
    set_usage_off: "表示しない",
    set_usage_threshold: "トークン",
    set_usage_cap: "タスクごとのトークン上限（0 = 上限なし）",
    set_usage_cap_hint: "上限を超えるとMokaが警告して停止します（フリーズしません）——支出は常にあなたの管理下にあります。",
    set_balance_btn: "💰 残高を確認",
    set_balance_unsupported: "このプロバイダーはAPIで残高を公開していません。公式パネルでご確認ください：",
    set_balance_open_panel: "プロバイダーのパネルを開く",
    set_model_btn: "モデルを変更",
    task_translate: "翻訳（抜粋）",
    task_translate_page: "ページ翻訳",
    task_translate_page_image: "ページ翻訳（画像）",
    tele_charts_title: "支出の推移（14日間）",
    tele_charts_cost: "費用（US$）",
    tele_charts_tokens: "トークン",
    tele_charts_all: "すべて",
    tele_charts_empty: "グラフを描くデータがまだ足りません — Mokaをもうしばらくご利用ください。",
    tele_mural_btn: "🏆 AIウォール",
    usage_ok: "OK",
    usage_copy: "コピー",
    usage_copied: "コピーしました ✓",
    usage_telemetry_note: "支出はテレメトリーページに保存されます。",
    tele_total_all: "累計（この端末）",
    tele_total_7: "直近7日間",
    tele_total_30: "直近30日間",
    task_translate_speech: "読み上げ用翻訳",
    task_explain: "解説（抜粋）",
    task_explain_page: "ページ解説",
    task_ask: "本への質問",
    task_summarize_page: "ページ要約",
    task_summarize_book: "本の要約",
    task_tts: "ニューラル音声（TTS）",
    task_test: "接続テスト",
    task_video_explain: "動画：クイック解説",
    task_video_summarize: "動画：要約",
    task_video_characters: "動画：登場人物",
    task_video_political: "動画：政治的背景",
    task_video_critique: "動画：批評",
    task_video_correct: "動画：修正済み文字起こし",
    task_video_ask: "動画：質問",
  },
  ko: {
    tele_nav: "AI 및 텔레메트리",
    tele_page_title: "귀하의 AI",
    tele_intro:
      "AI 관리 페이지: 등록된 키를 보고, 각 키의 모델을 바꾸고, 각 작업이 얼마나 썼는지 추적하세요. 모든 기록은 기기에만 저장됩니다.",
    tele_your_ais: "등록된 AI",
    tele_no_ais: "아직 등록된 AI 키가 없습니다. 첫 키를 추가하여 시작하세요.",
    tele_add_key: "➕ AI 키 추가",
    tele_spend_title: "📊 사용 지출",
    tele_ai_spent: "이 AI의 지출",
    tele_open_settings: "⚙️ 전체 설정 열기",
    tele_banner_sub: "AI를 보고, 모델을 바꾸고, 지출을 추적하세요",
    tele_total: "총 지출",
    tele_by_task: "작업별",
    tele_by_provider: "AI(제공자)별",
    tele_by_model: "모델별",
    tele_history: "기록",
    tele_clear: "기록 지우기",
    tele_clear_confirm: "전체 사용 기록을 삭제할까요? 되돌릴 수 없습니다(기록은 이 기기에만 저장됩니다).",
    tele_export_csv: "CSV 다운로드",
    tele_currency: "현지 통화",
    tele_approx: "추정치 — 환율과 가격은 대략적이며 공식 청구서가 아닙니다.",
    tele_empty: "아직 기록이 없습니다. 번역, 설명, 질문, 음성, 영상을 사용하면 여기에 표시됩니다.",
    tele_tokens: "토큰",
    tele_calls: "회 호출",
    tele_cost: "비용",
    tele_task: "작업",
    tele_provider: "AI",
    tele_model: "모델",
    tele_status: "상태",
    tele_ok: "정상",
    tele_err: "오류",
    usage_title: "AI 사용량",
    usage_in: "입력",
    usage_out: "출력",
    usage_cost: "예상 비용",
    usage_dontshow: "다시 보지 않기",
    usage_view: "텔레메트리 보기",
    usage_cap_warning: "⚠️ 작업당 토큰 상한을 초과했습니다!",
    usage_error_note: "⚠️ 작업이 실패했습니다 — 키가 잘못되었거나 크레딧이 부족할 수 있습니다.",
    usage_estimated: "추정",
    set_usage_title: "💸 사용량 경고와 상한",
    set_usage_popup: "사용량 알림(팝업)",
    set_usage_always: "항상 표시",
    set_usage_above: "이 값 이상일 때만",
    set_usage_off: "표시 안 함",
    set_usage_threshold: "토큰",
    set_usage_cap: "작업당 토큰 상한 (0 = 무제한)",
    set_usage_cap_hint: "작업이 상한을 넘기면 Moka가 알려주고 멈춥니다(멈춤 현상 없음) — 지출은 항상 귀하가 통제합니다.",
    set_balance_btn: "💰 잔액 확인",
    set_balance_unsupported: "이 제공자는 API로 잔액을 공개하지 않습니다. 공식 대시보드를 확인하세요:",
    set_balance_open_panel: "제공자 대시보드 열기",
    set_model_btn: "모델 변경",
    task_translate: "번역(발췌)",
    task_translate_page: "페이지 번역",
    task_translate_page_image: "페이지 번역(이미지)",
    tele_charts_title: "지출 추이(14일)",
    tele_charts_cost: "비용(US$)",
    tele_charts_tokens: "토큰",
    tele_charts_all: "전체",
    tele_charts_empty: "그래프를 그릴 데이터가 아직 부족합니다 — Moka를 조금 더 사용해 주세요.",
    tele_mural_btn: "🏆 AI 월",
    usage_ok: "OK",
    usage_copy: "복사",
    usage_copied: "복사됨 ✓",
    usage_telemetry_note: "지출이 텔레메트리 페이지에 저장됩니다.",
    tele_total_all: "전체 (이 기기)",
    tele_total_7: "최근 7일",
    tele_total_30: "최근 30일",
    task_translate_speech: "음성용 번역",
    task_explain: "설명(발췌)",
    task_explain_page: "페이지 설명",
    task_ask: "책에 대한 질문",
    task_summarize_page: "페이지 요약",
    task_summarize_book: "책 요약",
    task_tts: "뉴럴 음성(TTS)",
    task_test: "연결 테스트",
    task_video_explain: "영상: 빠른 설명",
    task_video_summarize: "영상: 요약",
    task_video_characters: "영상: 인물",
    task_video_political: "영상: 정치적 맥락",
    task_video_critique: "영상: 비평",
    task_video_correct: "영상: 교정된 스크립트",
    task_video_ask: "영상: 질문",
  },
  ar: {
    tele_nav: "ذكاءاتك والقياسات",
    tele_page_title: "ذكاءاتك",
    tele_intro:
      "صفحة التحكم في ذكاءاتك: اعرض المفاتيح المسجلة، وبدّل نموذج كل منها، وتابع كم أنفقت كل مهمة. كل شيء يُسجَّل على جهازك فقط.",
    tele_your_ais: "الذكاءات المسجلة",
    tele_no_ais: "لم تسجّل أي مفتاح ذكاء اصطناعي بعد. أضف الأول للبدء.",
    tele_add_key: "➕ إضافة مفتاح ذكاء اصطناعي",
    tele_spend_title: "📊 الإنفاق حسب الاستخدام",
    tele_ai_spent: "إنفاق هذا الذكاء",
    tele_open_settings: "⚙️ فتح كل الإعدادات",
    tele_banner_sub: "اعرض ذكاءاتك وبدّل النماذج وتابع الإنفاق",
    tele_total: "إجمالي الإنفاق",
    tele_by_task: "حسب المهمة",
    tele_by_provider: "حسب الذكاء الاصطناعي (المزوّد)",
    tele_by_model: "حسب النموذج",
    tele_history: "السجل",
    tele_clear: "مسح السجل",
    tele_clear_confirm: "حذف كل سجل الإنفاق؟ لا يمكن التراجع (السجلات محفوظة على هذا الجهاز فقط).",
    tele_export_csv: "تنزيل CSV",
    tele_currency: "العملة المحلية",
    tele_approx: "قيم تقديرية — أسعار صرف وأسعار تقريبية، وليست فاتورة رسمية.",
    tele_empty: "لا إنفاق بعد. استخدم الترجمة أو الشرح أو الأسئلة أو الصوت أو الفيديو — سيظهر كل استهلاك هنا.",
    tele_tokens: "رموز",
    tele_calls: "استدعاءات",
    tele_cost: "التكلفة",
    tele_task: "المهمة",
    tele_provider: "AI",
    tele_model: "النموذج",
    tele_status: "الحالة",
    tele_ok: "جيد",
    tele_err: "خطأ",
    usage_title: "استهلاك الذكاء الاصطناعي",
    usage_in: "مدخلات",
    usage_out: "مخرجات",
    usage_cost: "التكلفة التقديرية",
    usage_dontshow: "لا أريد رؤية هذا مجددًا",
    usage_view: "عرض القياسات",
    usage_cap_warning: "⚠️ تجاوزت حد الرموز لكل مهمة!",
    usage_error_note: "⚠️ فشلت المهمة — قد يكون المفتاح غير صالح أو الرصيد نفد.",
    usage_estimated: "تقديري",
    set_usage_title: "💸 تنبيهات الاستهلاك والحد الأقصى",
    set_usage_popup: "تقرير الاستهلاك (نافذة منبثقة)",
    set_usage_always: "إظهار دائمًا",
    set_usage_above: "فقط عند تجاوز",
    set_usage_off: "عدم الإظهار أبدًا",
    set_usage_threshold: "رمز",
    set_usage_cap: "حد الرموز لكل مهمة (0 = بلا حد)",
    set_usage_cap_hint: "إذا تجاوزت مهمة الحد، ينبهك Moka ويوقفها دون تجمّد — تبقى متحكمًا في إنفاقك.",
    set_balance_btn: "💰 عرض الرصيد",
    set_balance_unsupported: "هذا المزوّد لا يعرض الرصيد عبر API. راجع لوحته الرسمية:",
    set_balance_open_panel: "فتح لوحة المزوّد",
    set_model_btn: "تغيير النموذج",
    task_translate: "ترجمة (مقطع)",
    task_translate_page: "ترجمة صفحة",
    task_translate_page_image: "ترجمة صفحة (صورة)",
    tele_charts_title: "تطور الإنفاق (14 يومًا)",
    tele_charts_cost: "التكلفة (دولار)",
    tele_charts_tokens: "الرموز",
    tele_charts_all: "الكل",
    tele_charts_empty: "لا توجد بيانات كافية للرسوم البيانية بعد — واصل استخدام Moka.",
    tele_mural_btn: "🏆 جدار الذكاء الاصطناعي",
    usage_ok: "OK",
    usage_copy: "نسخ",
    usage_copied: "تم النسخ ✓",
    usage_telemetry_note: "يتم حفظ نفقاتك في صفحة القياس عن بُعد.",
    tele_total_all: "منذ البداية (هذا الجهاز)",
    tele_total_7: "آخر 7 أيام",
    tele_total_30: "آخر 30 يومًا",
    task_translate_speech: "ترجمة للقراءة الصوتية",
    task_explain: "شرح (مقطع)",
    task_explain_page: "شرح صفحة",
    task_ask: "سؤال عن الكتاب",
    task_summarize_page: "ملخص صفحة",
    task_summarize_book: "ملخص الكتاب",
    task_tts: "صوت عصبي (TTS)",
    task_test: "اختبار الاتصال",
    task_video_explain: "فيديو: شرح سريع",
    task_video_summarize: "فيديو: ملخص",
    task_video_characters: "فيديو: الشخصيات",
    task_video_political: "فيديو: السياق السياسي",
    task_video_critique: "فيديو: نقد",
    task_video_correct: "فيديو: نص مفرّغ مصحّح",
    task_video_ask: "فيديو: سؤال",
  },
  hi: {
    tele_nav: "आपकी AI और टेलीमेट्री",
    tele_page_title: "आपकी AI",
    tele_intro:
      "आपकी AI नियंत्रण पृष्ठ: पंजीकृत कुंजियाँ देखें, हर एक का मॉडल बदलें और जानें कि हर कार्य पर कितना ख़र्च हुआ। सब कुछ सिर्फ़ आपके डिवाइस पर दर्ज होता है।",
    tele_your_ais: "पंजीकृत AI",
    tele_no_ais: "अभी कोई AI कुंजी पंजीकृत नहीं है। शुरू करने के लिए पहली जोड़ें।",
    tele_add_key: "➕ AI कुंजी जोड़ें",
    tele_spend_title: "📊 उपयोग अनुसार ख़र्च",
    tele_ai_spent: "इस AI का ख़र्च",
    tele_open_settings: "⚙️ पूरी सेटिंग्स खोलें",
    tele_banner_sub: "अपनी AI देखें, मॉडल बदलें, हर ख़र्च देखें",
    tele_total: "कुल ख़र्च",
    tele_by_task: "कार्य अनुसार",
    tele_by_provider: "AI (प्रदाता) अनुसार",
    tele_by_model: "मॉडल अनुसार",
    tele_history: "इतिहास",
    tele_clear: "इतिहास साफ़ करें",
    tele_clear_confirm: "पूरा ख़र्च इतिहास हटाएँ? यह वापस नहीं हो सकता (रिकॉर्ड सिर्फ़ इसी डिवाइस पर हैं)।",
    tele_export_csv: "CSV डाउनलोड करें",
    tele_currency: "स्थानीय मुद्रा",
    tele_approx: "अनुमानित मान — विनिमय दर और क़ीमतें लगभग, आधिकारिक बिल नहीं।",
    tele_empty: "अभी कोई ख़र्च दर्ज नहीं। अनुवाद, व्याख्या, प्रश्न, आवाज़ या वीडियो इस्तेमाल करें — हर ख़र्च यहाँ दिखेगा।",
    tele_tokens: "टोकन",
    tele_calls: "कॉल",
    tele_cost: "लागत",
    tele_task: "कार्य",
    tele_provider: "AI",
    tele_model: "मॉडल",
    tele_status: "स्थिति",
    tele_ok: "ठीक",
    tele_err: "त्रुटि",
    usage_title: "AI खपत",
    usage_in: "इनपुट",
    usage_out: "आउटपुट",
    usage_cost: "अनुमानित लागत",
    usage_dontshow: "फिर न दिखाएँ",
    usage_view: "टेलीमेट्री देखें",
    usage_cap_warning: "⚠️ आपकी प्रति-कार्य टोकन सीमा पार हो गई!",
    usage_error_note: "⚠️ कार्य विफल रहा — कुंजी अमान्य हो सकती है या क्रेडिट ख़त्म।",
    usage_estimated: "अनुमानित",
    set_usage_title: "💸 खपत चेतावनी और सीमा",
    set_usage_popup: "खपत रिपोर्ट (पॉप-अप)",
    set_usage_always: "हमेशा दिखाएँ",
    set_usage_above: "सिर्फ़ इससे ऊपर",
    set_usage_off: "कभी न दिखाएँ",
    set_usage_threshold: "टोकन",
    set_usage_cap: "प्रति कार्य टोकन सीमा (0 = सीमा नहीं)",
    set_usage_cap_hint: "कार्य सीमा पार करे तो Moka चेताकर रोकता है, हैंग नहीं होता — ख़र्च आपके नियंत्रण में रहता है।",
    set_balance_btn: "💰 बैलेंस देखें",
    set_balance_unsupported: "यह प्रदाता API से बैलेंस नहीं देता। उसका आधिकारिक डैशबोर्ड देखें:",
    set_balance_open_panel: "प्रदाता डैशबोर्ड खोलें",
    set_model_btn: "मॉडल बदलें",
    task_translate: "अनुवाद (अंश)",
    task_translate_page: "पृष्ठ अनुवाद",
    task_translate_page_image: "पृष्ठ अनुवाद (चित्र)",
    tele_charts_title: "खर्च का रुझान (14 दिन)",
    tele_charts_cost: "लागत (US$)",
    tele_charts_tokens: "टोकन",
    tele_charts_all: "सभी",
    tele_charts_empty: "ग्राफ़ बनाने का डेटा अभी कम है — Moka का उपयोग जारी रखें।",
    tele_mural_btn: "🏆 AI दीवार",
    usage_ok: "OK",
    usage_copy: "कॉपी करें",
    usage_copied: "कॉपी हुआ ✓",
    usage_telemetry_note: "आपके खर्च आपके टेलीमेट्री पृष्ठ पर सहेजे जाते हैं।",
    tele_total_all: "शुरुआत से (इस डिवाइस पर)",
    tele_total_7: "पिछले 7 दिन",
    tele_total_30: "पिछले 30 दिन",
    task_translate_speech: "बोलने के लिए अनुवाद",
    task_explain: "व्याख्या (अंश)",
    task_explain_page: "पृष्ठ व्याख्या",
    task_ask: "किताब का प्रश्न",
    task_summarize_page: "पृष्ठ सारांश",
    task_summarize_book: "किताब सारांश",
    task_tts: "न्यूरल आवाज़ (TTS)",
    task_test: "कनेक्शन परीक्षण",
    task_video_explain: "वीडियो: त्वरित व्याख्या",
    task_video_summarize: "वीडियो: सारांश",
    task_video_characters: "वीडियो: पात्र",
    task_video_political: "वीडियो: राजनीतिक संदर्भ",
    task_video_critique: "वीडियो: आलोचना",
    task_video_correct: "वीडियो: सुधारी ट्रांसक्रिप्ट",
    task_video_ask: "वीडियो: प्रश्न",
  },
};

/** Idiomas suportados (mesma ordem/cobertura do ui-strings). */
export function tt(lang: string, key: TeleStringKey): string {
  const table = STRINGS[lang] ?? STRINGS.en ?? STRINGS["pt-BR"];
  return table[key] ?? STRINGS.en[key] ?? STRINGS["pt-BR"][key] ?? key;
}

/** Rótulo localizado de uma chave de tarefa do ledger. */
const TASK_KEY_MAP: Record<string, TeleStringKey> = {
  translate: "task_translate",
  "translate-page": "task_translate_page",
  "translate-page-image": "task_translate_page_image",
  "translate-speech": "task_translate_speech",
  explain: "task_explain",
  "explain-page": "task_explain_page",
  ask: "task_ask",
  "summarize-page": "task_summarize_page",
  "summarize-book": "task_summarize_book",
  tts: "task_tts",
  test: "task_test",
  "video-explain": "task_video_explain",
  "video-summarize": "task_video_summarize",
  "video-characters": "task_video_characters",
  "video-political": "task_video_political",
  "video-critique": "task_video_critique",
  "video-correct": "task_video_correct",
  "video-ask": "task_video_ask",
};

/** Nome bonito de uma tarefa do ledger (fallback: a própria chave). */
export function taskLabel(lang: string, task: string): string {
  const key = TASK_KEY_MAP[task];
  return key ? tt(lang, key) : task;
}
